// Mock data for demo mode when backend is unavailable

export const MOCK_USERS = [
  {
    id: 'user_1',
    email: 'maria@example.com',
    nombre: 'Maria',
    apellido: 'Gonzalez',
    avatar: 'https://picsum.photos/seed/maria/200',
    bio: 'Artesana de Oaxaca, especializada en textiles tradicionales',
    region: 'Valles Centrales',
    role: 'USER' as const,
    followersCount: 245,
    followingCount: 89,
    storiesCount: 12,
    createdAt: '2024-06-15T10:00:00Z',
  },
  {
    id: 'user_2',
    email: 'pedro@example.com',
    nombre: 'Pedro',
    apellido: 'Martinez',
    avatar: 'https://picsum.photos/seed/pedro/200',
    bio: 'Fotografo profesional documentando la Guelaguetza',
    region: 'Sierra Norte',
    role: 'USER' as const,
    followersCount: 523,
    followingCount: 156,
    storiesCount: 34,
    createdAt: '2024-05-20T10:00:00Z',
  },
  {
    id: 'user_3',
    email: 'lucia@example.com',
    nombre: 'Lucia',
    apellido: 'Hernandez',
    avatar: 'https://picsum.photos/seed/lucia/200',
    bio: 'Bailarina de danza folklorica, representante de Tuxtepec',
    region: 'Papaloapam',
    role: 'MODERATOR' as const,
    followersCount: 1205,
    followingCount: 234,
    storiesCount: 56,
    createdAt: '2024-04-10T10:00:00Z',
  },
  {
    id: 'user_4',
    email: 'carlos@example.com',
    nombre: 'Carlos',
    apellido: 'Lopez',
    avatar: 'https://picsum.photos/seed/carlos/200',
    bio: 'Mezcalero de tercera generacion',
    region: 'Valles Centrales',
    role: 'USER' as const,
    followersCount: 890,
    followingCount: 123,
    storiesCount: 23,
    createdAt: '2024-07-01T10:00:00Z',
  },
  {
    id: 'user_5',
    email: 'ana@example.com',
    nombre: 'Ana',
    apellido: 'Ruiz',
    avatar: 'https://picsum.photos/seed/ana/200',
    bio: 'Cocinera tradicional, mole negro es mi especialidad',
    region: 'Mixteca',
    role: 'USER' as const,
    followersCount: 456,
    followingCount: 78,
    storiesCount: 18,
    createdAt: '2024-06-01T10:00:00Z',
  },
  {
    id: 'user_6',
    email: 'roberto@example.com',
    nombre: 'Roberto',
    apellido: 'Sanchez',
    avatar: 'https://picsum.photos/seed/roberto/200',
    bio: 'Guia turistico certificado, 10 años de experiencia',
    region: 'Valles Centrales',
    role: 'USER' as const,
    followersCount: 678,
    followingCount: 234,
    storiesCount: 45,
    createdAt: '2024-03-15T10:00:00Z',
  },
  {
    id: 'user_7',
    email: 'elena@example.com',
    nombre: 'Elena',
    apellido: 'Vasquez',
    avatar: 'https://picsum.photos/seed/elena/200',
    bio: 'Artista de barro negro, tercera generacion en Coyotepec',
    region: 'Valles Centrales',
    role: 'USER' as const,
    followersCount: 1456,
    followingCount: 89,
    storiesCount: 67,
    createdAt: '2024-02-20T10:00:00Z',
  },
  {
    id: 'user_8',
    email: 'miguel@example.com',
    nombre: 'Miguel',
    apellido: 'Torres',
    avatar: 'https://picsum.photos/seed/miguel/200',
    bio: 'Musico de banda, trompetista en Flor de Piña',
    region: 'Costa',
    role: 'USER' as const,
    followersCount: 2340,
    followingCount: 456,
    storiesCount: 89,
    createdAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'user_9',
    email: 'sofia@example.com',
    nombre: 'Sofia',
    apellido: 'Mendez',
    avatar: 'https://picsum.photos/seed/sofia/200',
    bio: 'Diseñadora de moda con influencia oaxaqueña',
    region: 'Valles Centrales',
    role: 'MODERATOR' as const,
    followersCount: 3456,
    followingCount: 234,
    storiesCount: 123,
    createdAt: '2023-12-05T10:00:00Z',
  },
  {
    id: 'user_10',
    email: 'fernando@example.com',
    nombre: 'Fernando',
    apellido: 'Garcia',
    avatar: 'https://picsum.photos/seed/fernando/200',
    bio: 'Chef ejecutivo, especialista en cocina tradicional oaxaqueña',
    region: 'Valles Centrales',
    role: 'USER' as const,
    followersCount: 4567,
    followingCount: 123,
    storiesCount: 156,
    createdAt: '2023-11-20T10:00:00Z',
  },
  {
    id: 'user_11',
    email: 'guadalupe@example.com',
    nombre: 'Guadalupe',
    apellido: 'Ramirez',
    avatar: 'https://picsum.photos/seed/guadalupe/200',
    bio: 'Maestra de danza folklorica, 25 años de trayectoria',
    region: 'Sierra Sur',
    role: 'USER' as const,
    followersCount: 1890,
    followingCount: 345,
    storiesCount: 78,
    createdAt: '2024-04-01T10:00:00Z',
  },
  {
    id: 'user_12',
    email: 'jose@example.com',
    nombre: 'Jose',
    apellido: 'Morales',
    avatar: 'https://picsum.photos/seed/jose/200',
    bio: 'Productor de mezcal ancestral en Santa Catarina Minas',
    region: 'Valles Centrales',
    role: 'USER' as const,
    followersCount: 2100,
    followingCount: 178,
    storiesCount: 56,
    createdAt: '2024-05-10T10:00:00Z',
  },
  {
    id: 'user_13',
    email: 'carmen@example.com',
    nombre: 'Carmen',
    apellido: 'Diaz',
    avatar: 'https://picsum.photos/seed/carmen/200',
    bio: 'Tejedora en telar de cintura, preservando tecnicas zapotecas',
    region: 'Valles Centrales',
    role: 'USER' as const,
    followersCount: 890,
    followingCount: 67,
    storiesCount: 34,
    createdAt: '2024-06-20T10:00:00Z',
  },
  {
    id: 'user_14',
    email: 'ricardo@example.com',
    nombre: 'Ricardo',
    apellido: 'Jimenez',
    avatar: 'https://picsum.photos/seed/ricardo/200',
    bio: 'Cronista de la Guelaguetza, periodista cultural',
    region: 'Valles Centrales',
    role: 'MODERATOR' as const,
    followersCount: 5670,
    followingCount: 890,
    storiesCount: 234,
    createdAt: '2023-09-15T10:00:00Z',
  },
  {
    id: 'user_15',
    email: 'patricia@example.com',
    nombre: 'Patricia',
    apellido: 'Ortiz',
    avatar: 'https://picsum.photos/seed/patricia/200',
    bio: 'Directora de museo comunitario en Teotitlan del Valle',
    region: 'Valles Centrales',
    role: 'USER' as const,
    followersCount: 1234,
    followingCount: 456,
    storiesCount: 89,
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    id: 'user_16',
    email: 'alejandro@example.com',
    nombre: 'Alejandro',
    apellido: 'Velasco',
    avatar: 'https://picsum.photos/seed/alejandro/200',
    bio: 'Maestro tallador de alebrijes en San Martin Tilcajete',
    region: 'Valles Centrales',
    role: 'USER' as const,
    followersCount: 3456,
    followingCount: 234,
    storiesCount: 145,
    createdAt: '2023-10-10T10:00:00Z',
  },
  {
    id: 'user_17',
    email: 'laura@example.com',
    nombre: 'Laura',
    apellido: 'Cruz',
    avatar: 'https://picsum.photos/seed/laura/200',
    bio: 'Organizadora de tours gastronomicos por los mercados',
    region: 'Valles Centrales',
    role: 'USER' as const,
    followersCount: 2345,
    followingCount: 567,
    storiesCount: 98,
    createdAt: '2024-01-25T10:00:00Z',
  },
  {
    id: 'user_18',
    email: 'manuel@example.com',
    nombre: 'Manuel',
    apellido: 'Flores',
    avatar: 'https://picsum.photos/seed/manuel/200',
    bio: 'Historiador y escritor sobre tradiciones oaxaqueñas',
    region: 'Mixteca',
    role: 'USER' as const,
    followersCount: 4321,
    followingCount: 234,
    storiesCount: 167,
    createdAt: '2023-08-20T10:00:00Z',
  },
  {
    id: 'user_19',
    email: 'rosa@example.com',
    nombre: 'Rosa',
    apellido: 'Aguilar',
    avatar: 'https://picsum.photos/seed/rosa/200',
    bio: 'Bordadora de huipiles, tecnica de cadenilla',
    region: 'Istmo',
    role: 'USER' as const,
    followersCount: 1567,
    followingCount: 123,
    storiesCount: 45,
    createdAt: '2024-03-05T10:00:00Z',
  },
  {
    id: 'user_20',
    email: 'daniel@example.com',
    nombre: 'Daniel',
    apellido: 'Reyes',
    avatar: 'https://picsum.photos/seed/daniel/200',
    bio: 'Fotografo de naturaleza y paisajes de Oaxaca',
    region: 'Sierra Norte',
    role: 'USER' as const,
    followersCount: 6789,
    followingCount: 345,
    storiesCount: 234,
    createdAt: '2023-07-15T10:00:00Z',
  },
];

export const MOCK_STORIES = [
  {
    id: 'story_1',
    description: 'El colorido desfile de delegaciones por las calles del centro historico',
    mediaUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/2018_Desfile_Guelaguetza_Oaxaca_Mexico_11.jpg',
    mediaType: 'IMAGE' as const,
    thumbnailUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/2018_Desfile_Guelaguetza_Oaxaca_Mexico_11.jpg',
    duration: null,
    location: 'Centro Historico, Oaxaca',
    views: 1234,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    user: MOCK_USERS[0],
    _count: { likes: 89, comments: 12 },
    isLiked: false,
  },
  {
    id: 'story_2',
    description: 'Ensayo de la Danza de la Pluma en el Cerro del Fortin',
    mediaUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Danza_de_la_pluma.jpg',
    mediaType: 'IMAGE' as const,
    thumbnailUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Danza_de_la_pluma.jpg',
    duration: null,
    location: 'Cerro del Fortin',
    views: 2567,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    user: MOCK_USERS[1],
    _count: { likes: 156, comments: 23 },
    isLiked: true,
  },
  {
    id: 'story_3',
    description: 'Preparando el mole negro para la celebracion familiar',
    mediaUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Mole_negro_de_Oaxaca_con_arroz.jpg',
    mediaType: 'IMAGE' as const,
    thumbnailUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Mole_negro_de_Oaxaca_con_arroz.jpg',
    duration: null,
    location: 'Mercado de Abastos',
    views: 890,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    user: MOCK_USERS[4],
    _count: { likes: 67, comments: 8 },
    isLiked: false,
  },
  {
    id: 'story_4',
    description: 'Artesanias de barro negro de San Bartolo Coyotepec',
    mediaUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Barro_Negro_y_normal-San_Bartolo_Coyotepec-Oaxaca-Mexico.jpg',
    mediaType: 'IMAGE' as const,
    thumbnailUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Barro_Negro_y_normal-San_Bartolo_Coyotepec-Oaxaca-Mexico.jpg',
    duration: null,
    location: 'San Bartolo Coyotepec',
    views: 1456,
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    user: MOCK_USERS[0],
    _count: { likes: 234, comments: 45 },
    isLiked: true,
  },
  {
    id: 'story_5',
    description: 'La Guelaguetza en el Auditorio Guelaguetza',
    mediaUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Guelaguetza_Celebrations_27_July_2015.JPG',
    mediaType: 'IMAGE' as const,
    thumbnailUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Guelaguetza_Celebrations_27_July_2015.JPG',
    duration: null,
    location: 'Auditorio Guelaguetza',
    views: 5678,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    user: MOCK_USERS[2],
    _count: { likes: 456, comments: 78 },
    isLiked: false,
  },
];

export const MOCK_EVENTS = [
  {
    id: 'event_1',
    title: 'Desfile de Delegaciones',
    description: 'Gran desfile con las 8 regiones de Oaxaca por el centro historico',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/2018_Desfile_Guelaguetza_Oaxaca_Mexico_16.jpg',
    location: 'Centro Historico',
    latitude: 17.0614,
    longitude: -96.7256,
    startDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: null,
    category: 'DESFILE' as const,
    isOfficial: true,
    rsvpCount: 234,
    hasRSVP: false,
    hasReminder: false,
  },
  {
    id: 'event_2',
    title: 'Noche de Mezcal',
    description: 'Degustacion de los mejores mezcales artesanales de Oaxaca',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cata_mezcal.jpg',
    location: 'Plaza de la Danza',
    latitude: 17.0620,
    longitude: -96.7230,
    startDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: null,
    category: 'GASTRONOMIA' as const,
    isOfficial: true,
    rsvpCount: 156,
    hasRSVP: true,
    hasReminder: false,
  },
  {
    id: 'event_3',
    title: 'Calenda de Flores',
    description: 'Tradicional calenda con marmotas, música y flores',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/10_Calenda_en_San_Juan_Achiutla.jpg',
    location: 'Templo de Santo Domingo',
    latitude: 17.0660,
    longitude: -96.7240,
    startDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: null,
    category: 'CEREMONIA' as const,
    isOfficial: true,
    rsvpCount: 345,
    hasRSVP: false,
    hasReminder: true,
  },
  {
    id: 'event_4',
    title: 'Guelaguetza - Lunes del Cerro',
    description: 'Primer lunes del cerro en el Auditorio Guelaguetza',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Ritual_guelaguetza.JPG',
    location: 'Auditorio Guelaguetza',
    latitude: 17.0700,
    longitude: -96.7180,
    startDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: null,
    category: 'DANZA' as const,
    isOfficial: true,
    rsvpCount: 890,
    hasRSVP: false,
    hasReminder: false,
  },
  {
    id: 'event_5',
    title: 'Taller de Barro Negro',
    description: 'Aprende la tecnica ancestral del barro negro oaxaqueno',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Maestro_Alfarero,_San_Bartolo_Coyotepec,_Oaxaca,_México.jpg',
    location: 'San Bartolo Coyotepec',
    latitude: 16.9500,
    longitude: -96.7100,
    startDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: null,
    category: 'ARTESANIA' as const,
    isOfficial: false,
    rsvpCount: 45,
    hasRSVP: false,
    hasReminder: false,
  },
];

export const MOCK_COMMUNITIES = [
  {
    id: 'comm_1',
    name: 'Danzantes de Oaxaca',
    description: 'Comunidad de bailarines y amantes de las danzas tradicionales',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Danzantes_de_Mitla,_Oaxaca,_en_el_Museo_Nacional_de_Pueblos_Mágicos.jpg',
    category: 'DANZA',
    memberCount: 234,
    isPrivate: false,
    isMember: true,
  },
  {
    id: 'comm_2',
    name: 'Fotografos Guelaguetza',
    description: 'Compartimos las mejores fotos del festival',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Monte_Alban,_Oaxaca._Agosto_2009.JPG',
    category: 'ARTE',
    memberCount: 567,
    isPrivate: false,
    isMember: false,
  },
  {
    id: 'comm_3',
    name: 'Gastronomia Oaxaquena',
    description: 'Recetas, restaurantes y tradiciones culinarias',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Venta_de_chiles_en_Oaxaca.jpg',
    category: 'GASTRONOMIA',
    memberCount: 890,
    isPrivate: false,
    isMember: true,
  },
];

export const MOCK_ADMIN_STATS = {
  totalUsers: 12847,
  totalStories: 3567,
  totalComments: 18345,
  totalLikes: 45901,
  totalCommunities: 156,
  totalEvents: 89,
  newUsersToday: 234,
  newStoriesToday: 156,
  activeUsersToday: 4567,
};

export const MOCK_PRODUCTS = [
  // Artesanias
  {
    id: 'prod_1',
    name: 'Alebrije Jaguar Grande',
    description: 'Alebrije monumental tallado en madera de copal. Pieza unica de San Martin Tilcajete. Decorado con grecas zapotecas.',
    price: 3500,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/El_jaguar_reposa_en_la_mesa.jpg',
    category: 'ARTESANIA',
    seller: MOCK_USERS[15],
    stock: 1,
  },
  {
    id: 'prod_2',
    name: 'Alebrije Dragon',
    description: 'Figura fantastica de dragon con alas desmontables. Pintado a mano con tintes naturales.',
    price: 1200,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Alebrije_de_dragón.jpg',
    category: 'ARTESANIA',
    seller: MOCK_USERS[15],
    stock: 3,
  },
  {
    id: 'prod_3',
    name: 'Alebrije Reptil Colorido',
    description: 'Alebrije tallado a mano con forma de reptil fantástico, pintado con patrones detallados. Pieza única de madera de copal.',
    price: 650,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Alebrije_reptil.jpg',
    category: 'ARTESANIA',
    seller: MOCK_USERS[15],
    stock: 8,
  },
  // Mezcal
  {
    id: 'prod_4',
    name: 'Mezcal Espadin 750ml',
    description: 'Mezcal artesanal de agave espadin, 45% alc. vol. Producido en Santiago Matatlan, cuna del mezcal. Notas ahumadas con toques citricos.',
    price: 650,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Botella-mezcal-villanuevajpg.jpg',
    category: 'MEZCAL',
    seller: MOCK_USERS[11],
    stock: 25,
  },
  {
    id: 'prod_5',
    name: 'Mezcal Tobala 750ml',
    description: 'Mezcal premium de agave tobala silvestre, 48% alc. vol. Edicion limitada con sabor complejo y elegante.',
    price: 1800,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Mezcal_con_naranja_y_sal_de_gusano.jpg',
    category: 'MEZCAL',
    seller: MOCK_USERS[11],
    stock: 10,
  },
  {
    id: 'prod_6',
    name: 'Mezcal Pechuga 750ml',
    description: 'Mezcal de pechuga tradicional, destilado con frutas de temporada y pechuga de guajolote. Reserva especial.',
    price: 2500,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Mezcal_y_naranja.jpg',
    category: 'MEZCAL',
    seller: MOCK_USERS[11],
    stock: 5,
  },
  {
    id: 'prod_7',
    name: 'Set Degustacion Mezcal',
    description: 'Set de 4 mezcales artesanales de 100ml cada uno: Espadin, Tobala, Madrecuixe y Tepextate.',
    price: 1200,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cata_mezcal.jpg',
    category: 'MEZCAL',
    seller: MOCK_USERS[11],
    stock: 15,
  },
  // Textiles
  {
    id: 'prod_8',
    name: 'Huipil Bordado Istmo',
    description: 'Huipil tradicional del Istmo de Tehuantepec, bordado a mano con flores de colores vibrantes. Talla unica.',
    price: 3500,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Blusa_con_bordado_relleno_de_San_Felipe_Jalapa_de_Díaz_2.jpg',
    category: 'TEXTIL',
    seller: MOCK_USERS[18],
    stock: 2,
  },
  {
    id: 'prod_9',
    name: 'Rebozo de Telar',
    description: 'Rebozo tejido en telar de cintura con tecnica tradicional zapoteca. Algodon 100% natural tenido con cochinilla.',
    price: 1800,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/National_Museum_of_Ethnology,_Osaka_-_Backstrap_loom_-_San_Juan_Colorado,_Oaxaca_in_Mexico_-_Made_in_1985.jpg',
    category: 'TEXTIL',
    seller: MOCK_USERS[12],
    stock: 4,
  },
  {
    id: 'prod_10',
    name: 'Tapete Zapoteco Mediano',
    description: 'Tapete de lana tejido a mano en Teotitlan del Valle. Diseno de grecas tradicionales, 1.2m x 0.8m.',
    price: 2800,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Teotitlán_-_Teppiche.jpg',
    category: 'TEXTIL',
    seller: MOCK_USERS[12],
    stock: 3,
  },
  {
    id: 'prod_11',
    name: 'Tenate de Palma',
    description: 'Canasta tradicional de palma tejida a mano (Tenate). Ideal para guardar alimentos o como decoración.',
    price: 450,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/CanastasTenate006.JPG',
    category: 'TEXTIL',
    seller: MOCK_USERS[18],
    stock: 12,
  },
  // Ceramica
  {
    id: 'prod_12',
    name: 'Vaso Barro Negro',
    description: 'Vaso de barro negro bruñido de San Bartolo Coyotepec. Tecnica ancestral sin esmaltes.',
    price: 280,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Técnicas_de_acabado_del_barro_negro.JPG',
    category: 'CERAMICA',
    seller: MOCK_USERS[6],
    stock: 20,
  },
  {
    id: 'prod_13',
    name: 'Jarron Barro Negro Grande',
    description: 'Jarron decorativo de barro negro con grabados tradicionales. Altura 35cm.',
    price: 950,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cántaro_liso_de_barro_negro_de_Oaxaca_de_Juárez,_Oaxaca,_México.jpg',
    category: 'CERAMICA',
    seller: MOCK_USERS[6],
    stock: 5,
  },
  {
    id: 'prod_14',
    name: 'Comal de Barro Tradicional',
    description: 'Comal de barro rojo tradicional, ideal para hacer tortillas y tlayudas. Hecho a mano.',
    price: 380,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Comales_Oaxaca.jpg',
    category: 'CERAMICA',
    seller: MOCK_USERS[6],
    stock: 10,
  },
  {
    id: 'prod_15',
    name: 'Olla de Barro para Mezcal',
    description: 'Olla tradicional para servir mezcal, con dos jarritos incluidos. Barro negro pulido.',
    price: 550,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cántaro_liso_de_barro_negro_de_Oaxaca_de_Juárez,_Oaxaca,_México.jpg',
    category: 'CERAMICA',
    seller: MOCK_USERS[6],
    stock: 8,
  },
  // Joyeria
  {
    id: 'prod_16',
    name: 'Aretes Filigrana Plata',
    description: 'Aretes de plata 925 con tecnica de filigrana oaxaquena. Diseno de flores.',
    price: 850,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Silver_filigree_and_turqoise_earrings_by_Jos%C3%A9_Jorge_Garc%C3%ADa_Garc%C3%ADa.jpg',
    category: 'JOYERIA',
    seller: MOCK_USERS[0],
    stock: 6,
  },
  {
    id: 'prod_17',
    name: 'Collar Cruz de Yalalag',
    description: 'Collar artesanal con cruz de Yalalag y detalles en plata. Diseño tradicional de la Sierra Norte.',
    price: 1200,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Silver_Yalalag_style_cross_pendant_by_Cesar_Rodr%C3%ADguez_Z%C3%A1rate.jpg',
    category: 'JOYERIA',
    seller: MOCK_USERS[0],
    stock: 4,
  },
  {
    id: 'prod_18',
    name: 'Pulsera Ambar Chiapas',
    description: 'Pulsera con cuentas de ambar autentico de Chiapas y plata 925.',
    price: 680,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Collares_de_variscita_y_ámbar._Calcolítico._Museo_Arqueológico_Nacional_de_España.jpg',
    category: 'JOYERIA',
    seller: MOCK_USERS[0],
    stock: 9,
  },
  // Gastronomia
  {
    id: 'prod_19',
    name: 'Mole Negro 500g',
    description: 'Pasta de mole negro tradicional oaxaqueno. Receta familiar de mas de 50 años.',
    price: 180,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Mole_negro_oaxaqueño.jpg',
    category: 'GASTRONOMIA',
    seller: MOCK_USERS[4],
    stock: 30,
  },
  {
    id: 'prod_20',
    name: 'Set 7 Moles de Oaxaca',
    description: 'Los 7 moles tradicionales oaxaquenos: negro, rojo, coloradito, amarillo, verde, chichilo y manchamanteles.',
    price: 850,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Seven_moles_from_Oaxaca.jpg',
    category: 'GASTRONOMIA',
    seller: MOCK_USERS[4],
    stock: 15,
  },
  {
    id: 'prod_21',
    name: 'Chocolate Oaxaqueno 1kg',
    description: 'Tablillas de chocolate de metate tradicional con Pan de Yema. Cacao, canela y azucar. Para agua o leche.',
    price: 220,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pan_de_yema_y_chocolate_de_agua_-_Oaxaca_-_6.jpg',
    category: 'GASTRONOMIA',
    seller: MOCK_USERS[4],
    stock: 40,
  },
  {
    id: 'prod_22',
    name: 'Chapulines Preparados 250g',
    description: 'Chapulines tostados con chile, limon y sal. Snack tradicional oaxaqueno.',
    price: 120,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Chapulines_en_Oaxaca.jpg',
    category: 'GASTRONOMIA',
    seller: MOCK_USERS[4],
    stock: 50,
  },
  {
    id: 'prod_23',
    name: 'Quesillo Oaxaca 500g',
    description: 'Queso Oaxaca artesanal, tambien conocido como quesillo. Fresco del dia.',
    price: 150,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Quesillo_de_Oaxaca.png',
    category: 'GASTRONOMIA',
    seller: MOCK_USERS[4],
    stock: 20,
  },
  {
    id: 'prod_24',
    name: 'Tasajo Oaxaqueno 500g',
    description: 'Carne de res salada y secada al sol, tradicional de los Valles Centrales. Preparado con enfrijoladas.',
    price: 280,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Enfrijolada_con_tasajo.jpg',
    category: 'GASTRONOMIA',
    seller: MOCK_USERS[4],
    stock: 15,
  },
];

export const MOCK_EXPERIENCES = [
  {
    id: 'exp_1',
    title: 'Tour Mezcal Artesanal',
    description: 'Visita a palenques tradicionales y degustacion de mezcales',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Elaboración_de_mezcal_-_Alambique_y_destilador.jpg',
    price: 800,
    duration: '4 horas',
    maxGuests: 8,
    location: 'Santiago Matatlan',
    rating: 4.9,
    reviewCount: 45,
    host: MOCK_USERS[3],
  },
  {
    id: 'exp_2',
    title: 'Clase de Cocina Oaxaquena',
    description: 'Aprende a preparar mole negro y otros platillos tradicionales',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Mole_ingredients_(8266550590).jpg',
    price: 650,
    duration: '3 horas',
    maxGuests: 6,
    location: 'Centro Historico',
    rating: 4.8,
    reviewCount: 67,
    host: MOCK_USERS[4],
  },
  {
    id: 'exp_3',
    title: 'Taller de Textiles',
    description: 'Aprende tecnicas ancestrales de tejido en telar de cintura',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Tejedor_de_Teotitlán.jpg',
    price: 550,
    duration: '2.5 horas',
    maxGuests: 4,
    location: 'Teotitlan del Valle',
    rating: 5.0,
    reviewCount: 23,
    host: MOCK_USERS[0],
  },
];

export const MOCK_STREAMS = [
  {
    id: 'stream_1',
    title: 'En vivo desde el Auditorio Guelaguetza',
    description: 'Transmision en vivo de las presentaciones',
    thumbnailUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Guelaguetza_Celebrations_27_July_2015.JPG',
    isLive: true,
    viewerCount: 1234,
    host: MOCK_USERS[1],
    startedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'stream_2',
    title: 'Calenda en el Centro',
    description: 'Siguiendo la calenda por las calles de Oaxaca',
    thumbnailUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Calenda_en_San_Juan_Achiutla.jpg',
    isLive: true,
    viewerCount: 567,
    host: MOCK_USERS[2],
    startedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'stream_3',
    title: 'Preparacion del Mole',
    description: 'Cocinando mole negro en vivo',
    thumbnailUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Mole_negro_de_Oaxaca_con_arroz.jpg',
    isLive: false,
    viewerCount: 890,
    host: MOCK_USERS[4],
    startedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];
